"""initial schema

Revision ID: bf8b33c13520
Revises:
Create Date: 2026-07-22 10:37:37.473163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bf8b33c13520"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_user",
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "VOLUNTEER", "HACKER", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_password_reset_request", sa.DateTime(), nullable=True),
        sa.Column("last_activation_email_sent", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_account_user_email"), "account_user", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_account_user_first_name"), "account_user", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_account_user_last_name"), "account_user", ["last_name"], unique=False
    )
    op.create_table(
        "forms_form",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forms_question",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("question_order", sa.Integer(), nullable=False),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_index(
        op.f("ix_forms_question_label"), "forms_question", ["label"], unique=False
    )
    op.create_index(
        op.f("ix_forms_question_question_order"),
        "forms_question",
        ["question_order"],
        unique=False,
    )
    op.create_table(
        "meal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "day",
            sa.Enum("FRIDAY", "SATURDAY", "SUNDAY", name="weekday"),
            nullable=True,
        ),
        sa.Column(
            "meal_type",
            sa.Enum("BREAKFAST", "LUNCH", "DINNER", "SNACK", "MERCH", name="mealtype"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("day", "meal_type", name="unique_day_meal_type"),
    )
    op.create_table(
        "food_tracking",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("checkin_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account_user.uid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_food_tracking_meal_id"), "food_tracking", ["meal_id"], unique=False
    )
    op.create_index(
        op.f("ix_food_tracking_user_id"), "food_tracking", ["user_id"], unique=False
    )
    op.create_table(
        "forms_application",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"],
            ["account_user.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_forms_application_application_id"),
        "forms_application",
        ["application_id"],
        unique=True,
    )
    op.create_table(
        "forms_answer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=True),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column(
            "answer", sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["forms_application.application_id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["forms_question.question_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forms_answer_application_id"),
        "forms_answer",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forms_answer_question_id"),
        "forms_answer",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "forms_answerfile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=True),
        sa.Column(
            "original_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["forms_application.application_id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["forms_question.question_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forms_answerfile_application_id"),
        "forms_answerfile",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forms_answerfile_question_id"),
        "forms_answerfile",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "forms_hackathonapplicant",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACCOUNT_INACTIVE",
                "NOT_APPLIED",
                "APPLYING",
                "APPLIED",
                "UNDER_REVIEW",
                "WAITLISTED",
                "ACCEPTED",
                "REJECTED",
                "ACCEPTED_INVITE",
                "REJECTED_INVITE",
                "SCANNED_IN",
                "WALK_IN",
                "WALK_IN_SUBMITTED",
                name="statusenum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["forms_application.application_id"],
        ),
        sa.PrimaryKeyConstraint("application_id"),
    )
    op.create_index(
        op.f("ix_forms_hackathonapplicant_status"),
        "forms_hackathonapplicant",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_forms_hackathonapplicant_status"),
        table_name="forms_hackathonapplicant",
    )
    op.drop_table("forms_hackathonapplicant")
    op.drop_index(
        op.f("ix_forms_answerfile_question_id"), table_name="forms_answerfile"
    )
    op.drop_index(
        op.f("ix_forms_answerfile_application_id"), table_name="forms_answerfile"
    )
    op.drop_table("forms_answerfile")
    op.drop_index(op.f("ix_forms_answer_question_id"), table_name="forms_answer")
    op.drop_index(op.f("ix_forms_answer_application_id"), table_name="forms_answer")
    op.drop_table("forms_answer")
    op.drop_index(
        op.f("ix_forms_application_application_id"), table_name="forms_application"
    )
    op.drop_table("forms_application")
    op.drop_index(op.f("ix_food_tracking_user_id"), table_name="food_tracking")
    op.drop_index(op.f("ix_food_tracking_meal_id"), table_name="food_tracking")
    op.drop_table("food_tracking")
    op.drop_table("meal")
    op.drop_index(op.f("ix_forms_question_question_order"), table_name="forms_question")
    op.drop_index(op.f("ix_forms_question_label"), table_name="forms_question")
    op.drop_table("forms_question")
    op.drop_table("forms_form")
    op.drop_index(op.f("ix_account_user_last_name"), table_name="account_user")
    op.drop_index(op.f("ix_account_user_first_name"), table_name="account_user")
    op.drop_index(op.f("ix_account_user_email"), table_name="account_user")
    op.drop_table("account_user")
    bind = op.get_bind()
    for enum_name in ("statusenum", "mealtype", "weekday", "userrole"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
