# Generated by Django 3.2.7 on 2021-09-23 00:13

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import hacktheback.messenger.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the template. This is not included in the template.",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of the template. This is not included in the template.",
                        null=True,
                    ),
                ),
                (
                    "plaintext_message",
                    models.TextField(
                        help_text="The plain-text alternative. It is important to have this as some e-mail clients won't render HTML e-mails.",
                        null=True,
                    ),
                ),
                (
                    "html_message_as_mjml",
                    models.TextField(
                        validators=[
                            hacktheback.messenger.validators.validate_mjml
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sender_note", models.TextField(null=True)),
                ("is_test", models.BooleanField(default=False)),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="messages", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the template. This is not included in the template.",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of the template. This is not included in the template.",
                        null=True,
                    ),
                ),
                (
                    "plaintext_message",
                    models.TextField(
                        help_text="The plain-text alternative. It is important to have this as some e-mail clients won't render HTML e-mails.",
                        null=True,
                    ),
                ),
                (
                    "html_message_as_mjml",
                    models.TextField(
                        validators=[
                            hacktheback.messenger.validators.validate_mjml
                        ]
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical email template",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=256)),
                (
                    "metadata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email",
                        to="messenger.message",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="messenger.historicalemailtemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
