# Generated by Django 3.2.7 on 2021-09-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_alter_answeroption_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="formresponse",
            options={"ordering": ["-updated_at"]},
        ),
    ]
