# Generated by Django 3.2.7 on 2021-09-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_auto_20210922_2315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathonapplicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLYING", "Applying"),
                    ("APPLIED", "Applied"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("WAITLISTED", "Waitlisted"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED_INVITE", "Accepted Invitation"),
                    ("REJECTED_INVITE", "Rejected Invitation"),
                ],
                default="APPLIED",
                max_length=15,
            ),
        ),
    ]
