# Generated by Django 3.2.7 on 2021-09-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_alter_hackathonapplicant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="formresponse",
            name="admin_notes",
            field=models.TextField(null=True),
        ),
    ]
