# Generated by Django 3.2.7 on 2023-09-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formresponse_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonapplicant',
            name='status',
            field=models.CharField(choices=[('APPLYING', 'Applying'), ('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('WAITLISTED', 'Waitlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ACCEPTED_INVITE', 'Accepted Invitation'), ('REJECTED_INVITE', 'Rejected Invitation'), ('SCANNED_IN', 'Scanned In')], default='APPLIED', max_length=15),
        ),
    ]
