# Generated by Django 3.2.7 on 2024-07-08 01:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_hackathonapplicant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('day', models.IntegerField()),
                ('end_time', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HackerFoodTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='forms.formresponse')),
                ('serving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='forms.food')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
