# Generated by Django 3.2.7 on 2024-07-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_food_hackerfoodtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
