# Generated by Django 3.2.7 on 2024-07-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_food_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hackerfoodtracking',
            unique_together={('application', 'serving')},
        ),
    ]
