# Generated by Django 3.2.25 on 2024-09-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_hackerfoodtracking_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='end_time',
        ),
        migrations.AddField(
            model_name='food',
            name='serving',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hackathonapplicant',
            name='status',
            field=models.CharField(choices=[('APPLYING', 'Applying'), ('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('WAITLISTED', 'Waitlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ACCEPTED_INVITE', 'Accepted Invitation'), ('REJECTED_INVITE', 'Rejected Invitation'), ('SCANNED_IN', 'Scanned In'), ('WALK_IN', 'Walked In'), ('WALK_IN_SUBMIT', 'Walked In (Submitted)')], default='APPLIED', max_length=15),
        ),
    ]
