# Generated by Django 3.2.25 on 2024-09-29 20:10

from django.db import migrations


def create_foods(apps, schema_editor):
    Food = apps.get_model("forms", "Food")

    db_alias = schema_editor.connection.alias
    Food.objects.all().delete()
    Food.objects.using(db_alias).bulk_create([
        Food(name="Dinner", day=1),
        Food(name="Breakfast", day=2),
        Food(name="Lunch", day=2),
        Food(name="Dinner", day=2),
        Food(name="Breakfast", day=3),
        Food(name="Lunch", day=3),
    ])

def delete_foods(apps, schema_editor):
    Food = apps.get_model("forms", "Food")

    db_alias = schema_editor.connection.alias
    Food.objects.all().using(db_alias).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20240926_0122'),
    ]

    operations = [
        migrations.RunPython(create_foods, reverse_code=delete_foods),
    ]
